import * as mongoose from 'mongoose';

export const turbineSchema = new mongoose.Schema({
    id:{type:String, required:false},
    AddGas:{type:Boolean, required:false},
    AddPlasma:{type:Boolean, required:false},
    AutoGenerateBlastFurnaceRecipes:{type:Boolean, required:false},
    BlastFurnaceRequired:{type:Boolean, required:false},
    BlastFurnaceTemp:{type:Number, required:false},
    ChemicalFormula:{type:String, required:false},
    DensityDivider:{type:Number, required:false},
    DensityMultiplier:{type:Number, required:false},
    Density:{type:Number, required:false},
    DyeColor:{type:String, required:false},
    EnchantmentLevel:{type:Number, required:false},
    Enchantment:{type:String, required:false},
    FuelPower:{type:Number, required:false},
    FuelType:{type:Number, required:false},
    GasTemp:{type:Number, required:false},
    HasParentMod:{type:Boolean, required:false},
    HeatDamage:{type:Number, required:false},
    ListMaterialByProducts:{type:String, required:false},
    ListMaterialReRegistrations:{type:String, required:false},
    ListSubTags:{type:String, required:false},
    ListTCAspectAmounts:{type:String, required:false},
    ListTCAspects:{type:String, required:false},
    MatRGBA:{type:String, required:false},
    MaterialArcSmeltInto:{type:String, required:false},
    MaterialDirectSmeltInto:{type:String, required:false},
    MaterialID:{type:Number, required:false},
    MaterialMacerateInto:{type:String, required:false},
    MaterialName:{type:String, required:false},
    MaterialSmeltInto:{type:String, required:false},
    MaterialTypes:{type:Number, required:false},
    MeltingPoint:{type:Number, required:false},
    OreByProductMultiplier:{type:Number, required:false},
    OreMultiplier:{type:Number, required:false},
    OreSmeltingMultiplier:{type:Number, required:false},
    OreValue:{type:Number, required:false},
    ToolDurability:{type:Number, required:false},
    ToolQuality:{type:Number, required:false},
    ToolSpeed:{type:Number, required:false},
    Transparent:{type:Boolean, required:false},
    Unificatable:{type:Boolean, required:false},

})
export interface Turbine extends mongoose.Document {
    id:String,
    AddGas:Boolean,
    AddPlasma:Boolean,
    AutoGenerateBlastFurnaceRecipes:Boolean,
    BlastFurnaceRequired:Boolean,
    BlastFurnaceTemp:Number,
    ChemicalFormula:String,
    DensityDivider:Number,
    DensityMultiplier:Number,
    Density:Number,
    DyeColor:String,
    EnchantmentLevel:Number,
    Enchantment:String,
    FuelPower:Number,
    FuelType:Number,
    GasTemp:Number,
    HasParentMod:Boolean,
    HeatDamage:Number,
    ListMaterialByProducts:String,
    ListMaterialReRegistrations:String,
    ListSubTags:String,
    ListTCAspectAmounts:String,
    ListTCAspects:String,
    MatRGBA:String,
    MaterialArcSmeltInto:String,
    MaterialDirectSmeltInto:String,
    MaterialID:Number,
    MaterialMacerateInto:String,
    MaterialName:String,
    MaterialSmeltInto:String,
    MaterialTypes:Number,
    MeltingPoint:Number,
    OreByProductMultiplier:Number,
    OreMultiplier:Number,
    OreSmeltingMultiplier:Number,
    OreValue:Number,
    ToolDurability:Number,
    ToolQuality:Number,
    ToolSpeed:Number,
    Transparent:Boolean,
    Unificatable:Boolean
}